name: ci

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        py-version:
          - '3.11'
          - '3.14'
    name: Python ${{ matrix.py-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Use Python ${{ matrix.py-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.py-version }}
          architecture: x64

      - name: Install Spectral with test dependencies
        run: |
          pip install -e .[dev]

      - name: Run tests
        run: |
          pytest --cov=specktral --cov-branch --cov-report=xml tests

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        if: matrix.py-version == '3.14'
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: brownbaerchen/Specktral

  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    name: Pre-commit hooks
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.14
          architecture: x64

      - name: Install Spectral with test dependencies
        run: |
          pip install .[dev]

      - name: Run tests
        run: |
          pre-commit run --all-files
